sudo: false
language: ruby
rvm:
  - 2.6
addons:
  apt:
    packages:
    - libzmq3-dev
cache:
  - apt
  - bundler
before_install:
  - gem install bundler --version 1.17.3
  - bundle --version
  - gem update --system
  - gem --version
branches:
  only:
    - master
