source 'https://supermarket.chef.io'

cookbook 'omnibus', git: 'https://github.com/chef-cookbooks/omnibus.git'

# Uncomment to use the latest version of the Omnibus cookbook from GitHub
# cookbook 'omnibus', github: 'opscode-cookbooks/omnibus'

group :integration do
  cookbook 'apt',      '~> 2.3'
  cookbook 'freebsd',  '~> 0.1'
  cookbook 'yum-epel', '~> 0.3'
end
