source 'https://rubygems.org'

gem 'omnibus', github: 'chef/omnibus'
gem 'omnibus-software', github: 'chef/omnibus-software'

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle install --without development` to speed up build times.
group :development do
  gem 'berkshelf'
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'winrm-fs'
  gem 'kitchen-wpar', git: 'git@github.com:chef/kitchen-wpar'
end
