name 'push_jobs_acceptance'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures push-jobs-acceptance'
long_description 'Installs/Configures push-jobs-acceptance'
version '0.1.0'

depends 'chef-server'
depends 'chef-server-ctl'
depends 'push-jobs'
depends 'hostsfile'
